import { projects, documents, buildTasks } from "@/db/schema";
import type { IntegrityReport } from "@/lib/blueprint-engine/integrity-report";
import {
  PROJECT_DOCUMENT_DEFINITIONS,
  PROJECT_DOCUMENT_TITLES_BY_TYPE,
} from "@/lib/project-document-types";

const DOC_ORDER = PROJECT_DOCUMENT_DEFINITIONS.map((doc) => doc.type);
const DOC_TITLES = PROJECT_DOCUMENT_TITLES_BY_TYPE;

type Project = typeof projects.$inferSelect;
type Document = typeof documents.$inferSelect;
type BuildTask = typeof buildTasks.$inferSelect;

/** Renders the full project blueprint (all documents + task roadmap) as Markdown. */
export function buildProjectBlueprintMarkdown(
  project: Project,
  docs: Document[],
  tasks: BuildTask[],
  integrityReport: IntegrityReport,
  options: { forceExport?: boolean } = {}
): string {
  const exportDate = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const mdParts: string[] = [];

  mdParts.push(`# ${project.name} — Complete Blueprint`);
  mdParts.push(`**Generated by SkolaTech PRD Studio**  `);
  mdParts.push(`**Date:** ${exportDate}  `);
  mdParts.push(`**Security Level:** ${project.securityLevel ?? "standard"}  `);
  mdParts.push(`**Blueprint Readiness:** ${project.readinessScore ?? 0}%  `);
  mdParts.push(`**Security Score:** ${project.securityScore ?? 0}/100`);
  mdParts.push("");
  mdParts.push("---");
  mdParts.push("");

  if (options.forceExport && integrityReport.hasBlockingErrors) {
    mdParts.push("> ⚠️ **Exported with unresolved integrity errors.** The following conflicts were not resolved before export — verify them before treating this blueprint as build-ready.");
    mdParts.push(">");
    for (const issue of integrityReport.issues.filter((i) => i.severity === "error")) {
      mdParts.push(`> - **${issue.documentTypes.map((t) => DOC_TITLES[t as keyof typeof DOC_TITLES] ?? t).join(", ") || "Project model"}:** ${issue.message}`);
    }
    mdParts.push("");
    mdParts.push("---");
    mdParts.push("");
  }

  const stack = (project.stackPreferences as Record<string, string>) ?? {};
  const stackRows = Object.entries(stack).filter(([, v]) => v && v !== "None");
  if (stackRows.length > 0) {
    mdParts.push("## Technology Stack");
    mdParts.push("");
    mdParts.push("| Layer | Choice |");
    mdParts.push("|-------|--------|");
    stackRows.forEach(([k, v]) => mdParts.push(`| ${k.charAt(0).toUpperCase() + k.slice(1)} | ${v} |`));
    mdParts.push("");
    mdParts.push("---");
    mdParts.push("");
  }

  mdParts.push("## Table of Contents");
  mdParts.push("");
  DOC_ORDER.forEach((type, i) => {
    const doc = docs.find((d) => d.type === type);
    const status = doc?.status === "ready" || doc?.status === "approved" ? "✅" : "⏳";
    mdParts.push(`${i + 1}. ${status} [${DOC_TITLES[type]}](#${DOC_TITLES[type].toLowerCase().replace(/[^a-z0-9]+/g, "-")})`);
  });
  if (tasks.length > 0) mdParts.push(`${DOC_ORDER.length + 1}. 📋 [Build Task Roadmap](#build-task-roadmap)`);
  mdParts.push("");
  mdParts.push("---");
  mdParts.push("");

  for (const type of DOC_ORDER) {
    const doc = docs.find((d) => d.type === type);
    mdParts.push(`# ${DOC_TITLES[type]}`);
    mdParts.push("");
    if (doc?.content) {
      mdParts.push(doc.content);
    } else {
      mdParts.push(`> ⏳ This document has not been generated yet.`);
    }
    mdParts.push("");
    mdParts.push("---");
    mdParts.push("");
  }

  if (tasks.length > 0) {
    mdParts.push("# Build Task Roadmap");
    mdParts.push("");
    mdParts.push(`Total tasks: **${tasks.length}** | Done: **${tasks.filter((t) => t.status === "done").length}** | In Progress: **${tasks.filter((t) => t.status === "in_progress").length}**`);
    mdParts.push("");

    const phases = [...new Set(tasks.map((t) => t.phase ?? "General"))];
    for (const phase of phases) {
      const phaseTasks = tasks.filter((t) => (t.phase ?? "General") === phase);
      mdParts.push(`## ${phase}`);
      mdParts.push("");
      mdParts.push("| Task | Priority | Status | Effort |");
      mdParts.push("|------|----------|--------|--------|");
      phaseTasks.forEach((t) => {
        mdParts.push(`| ${t.title} | ${t.priority ?? "medium"} | ${t.status ?? "backlog"} | ${t.estimatedEffort ?? "—"} |`);
      });
      mdParts.push("");
    }
  }

  return mdParts.join("\n");
}
