import { auth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { projects, documents, buildTasks, securityChecks } from "@/db/schema";
import { eq, and } from "drizzle-orm";

const DOC_ORDER = [
  "prd",
  "trd",
  "app_flow",
  "ux_brief",
  "backend_schema",
  "implementation_plan",
  "security_blueprint",
] as const;

const DOC_TITLES: Record<string, string> = {
  prd: "Product Requirements Document",
  trd: "Technical Requirements Document",
  app_flow: "App Flow",
  ux_brief: "UI/UX Design Brief",
  backend_schema: "Backend Schema",
  implementation_plan: "Implementation Plan",
  security_blueprint: "Security Blueprint",
};

interface Params {
  params: Promise<{ projectId: string }>;
}

export async function GET(req: NextRequest, { params }: Params) {
  const { projectId } = await params;
  const { userId } = await auth();
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const format = req.nextUrl.searchParams.get("format") ?? "markdown";

  const [project] = await db
    .select()
    .from(projects)
    .where(and(eq(projects.id, projectId), eq(projects.userId, userId)))
    .limit(1);
  if (!project) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const docs = await db.select().from(documents).where(eq(documents.projectId, projectId));
  const tasks = await db.select().from(buildTasks).where(eq(buildTasks.projectId, projectId));

  const exportDate = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  // ─── Build Markdown content ───────────────────────────────────────────
  const mdParts: string[] = [];

  // Cover
  mdParts.push(`# ${project.name} — Complete Blueprint`);
  mdParts.push(`**Generated by SkolaTech PRD Studio**  `);
  mdParts.push(`**Date:** ${exportDate}  `);
  mdParts.push(`**Security Level:** ${project.securityLevel ?? "standard"}  `);
  mdParts.push(`**Blueprint Readiness:** ${project.readinessScore ?? 0}%  `);
  mdParts.push(`**Security Score:** ${project.securityScore ?? 0}/100`);
  mdParts.push("");
  mdParts.push("---");
  mdParts.push("");

  // Stack summary
  const stack = (project.stackPreferences as Record<string, string>) ?? {};
  const stackRows = Object.entries(stack).filter(([, v]) => v && v !== "None");
  if (stackRows.length > 0) {
    mdParts.push("## Technology Stack");
    mdParts.push("");
    mdParts.push("| Layer | Choice |");
    mdParts.push("|-------|--------|");
    stackRows.forEach(([k, v]) => mdParts.push(`| ${k.charAt(0).toUpperCase() + k.slice(1)} | ${v} |`));
    mdParts.push("");
    mdParts.push("---");
    mdParts.push("");
  }

  // Table of contents
  mdParts.push("## Table of Contents");
  mdParts.push("");
  DOC_ORDER.forEach((type, i) => {
    const doc = docs.find((d) => d.type === type);
    const status = doc?.status === "ready" || doc?.status === "approved" ? "✅" : "⏳";
    mdParts.push(`${i + 1}. ${status} [${DOC_TITLES[type]}](#${DOC_TITLES[type].toLowerCase().replace(/[^a-z0-9]+/g, "-")})`);
  });
  if (tasks.length > 0) mdParts.push(`${DOC_ORDER.length + 1}. 📋 [Build Task Roadmap](#build-task-roadmap)`);
  mdParts.push("");
  mdParts.push("---");
  mdParts.push("");

  // Documents
  for (const type of DOC_ORDER) {
    const doc = docs.find((d) => d.type === type);
    mdParts.push(`# ${DOC_TITLES[type]}`);
    mdParts.push("");
    if (doc?.content) {
      mdParts.push(doc.content);
    } else {
      mdParts.push(`> ⏳ This document has not been generated yet.`);
    }
    mdParts.push("");
    mdParts.push("---");
    mdParts.push("");
  }

  // Build tasks
  if (tasks.length > 0) {
    mdParts.push("# Build Task Roadmap");
    mdParts.push("");
    mdParts.push(`Total tasks: **${tasks.length}** | Done: **${tasks.filter((t) => t.status === "done").length}** | In Progress: **${tasks.filter((t) => t.status === "in_progress").length}**`);
    mdParts.push("");

    const phases = [...new Set(tasks.map((t) => t.phase ?? "General"))];
    for (const phase of phases) {
      const phaseTasks = tasks.filter((t) => (t.phase ?? "General") === phase);
      mdParts.push(`## ${phase}`);
      mdParts.push("");
      mdParts.push("| Task | Priority | Status | Effort |");
      mdParts.push("|------|----------|--------|--------|");
      phaseTasks.forEach((t) => {
        mdParts.push(`| ${t.title} | ${t.priority ?? "medium"} | ${t.status ?? "backlog"} | ${t.estimatedEffort ?? "—"} |`);
      });
      mdParts.push("");
    }
  }

  const markdownContent = mdParts.join("\n");

  if (format === "markdown") {
    const slug = project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    return new NextResponse(markdownContent, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="${slug}-blueprint.md"`,
      },
    });
  }

  // ─── HTML export ─────────────────────────────────────────────────────
  const htmlContent = buildHtmlExport(project.name, exportDate, markdownContent, {
    readinessScore: project.readinessScore ?? 0,
    securityScore: project.securityScore ?? 0,
    securityLevel: project.securityLevel ?? "standard",
    stack: stackRows,
  });

  const slug = project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return new NextResponse(htmlContent, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${slug}-blueprint.html"`,
    },
  });
}

function buildHtmlExport(
  appName: string,
  date: string,
  markdown: string,
  meta: { readinessScore: number; securityScore: number; securityLevel: string; stack: [string, string][] }
) {
  // Convert markdown to HTML (basic conversion — Mermaid blocks stay as-is for the JS renderer)
  const html = markdownToHtml(markdown);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${appName} — Blueprint | SkolaTech PRD Studio</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <style>
    :root {
      --primary: #2d5a27;
      --primary-light: #4a7c42;
      --accent: #e8f5e3;
      --border: #e2e8e0;
      --text: #1a1a1a;
      --muted: #6b7280;
      --bg: #ffffff;
      --sidebar-bg: #1a2e18;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 14px;
      line-height: 1.7;
      color: var(--text);
      background: var(--bg);
      max-width: 1000px;
      margin: 0 auto;
      padding: 48px 32px;
    }
    @media print {
      body { padding: 24px; max-width: 100%; }
      .no-print { display: none !important; }
      h1, h2, h3 { break-after: avoid; }
      pre, table, .mermaid { break-inside: avoid; }
    }

    /* Cover */
    .cover {
      background: var(--sidebar-bg);
      color: white;
      border-radius: 16px;
      padding: 48px;
      margin-bottom: 48px;
    }
    .cover-brand { font-size: 11px; font-weight: 600; letter-spacing: 2px; text-transform: uppercase; color: rgba(255,255,255,0.5); margin-bottom: 12px; }
    .cover h1 { font-size: 36px; font-weight: 800; margin-bottom: 8px; }
    .cover-sub { color: rgba(255,255,255,0.6); font-size: 15px; margin-bottom: 32px; }
    .cover-meta { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; }
    .cover-stat { background: rgba(255,255,255,0.08); border-radius: 10px; padding: 16px; }
    .cover-stat-label { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: rgba(255,255,255,0.4); margin-bottom: 4px; }
    .cover-stat-value { font-size: 24px; font-weight: 700; color: #6fcf5a; }
    .cover-stat-value.warn { color: #f6a623; }
    .cover-stat-value.ok { color: #6fcf5a; }
    .cover-stat-value.neutral { color: white; font-size: 16px; }

    /* TOC */
    .toc { background: var(--accent); border: 1px solid var(--border); border-radius: 12px; padding: 24px 32px; margin-bottom: 48px; }
    .toc h2 { font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: var(--primary); margin-bottom: 16px; }
    .toc ol { padding-left: 20px; }
    .toc li { margin-bottom: 6px; }
    .toc a { color: var(--primary); text-decoration: none; font-weight: 500; }
    .toc a:hover { text-decoration: underline; }

    /* Doc sections */
    .doc-section { margin-bottom: 64px; }
    .doc-header {
      background: var(--accent);
      border-left: 4px solid var(--primary);
      border-radius: 0 8px 8px 0;
      padding: 16px 24px;
      margin-bottom: 32px;
    }
    .doc-header h1 { font-size: 22px; font-weight: 800; color: var(--primary); }
    .doc-divider { border: none; border-top: 2px solid var(--border); margin: 64px 0; }

    /* Typography */
    h1 { font-size: 28px; font-weight: 800; margin: 40px 0 16px; color: var(--text); line-height: 1.3; }
    h2 { font-size: 20px; font-weight: 700; margin: 32px 0 12px; color: var(--text); }
    h3 { font-size: 16px; font-weight: 600; margin: 24px 0 8px; color: var(--text); }
    h4 { font-size: 14px; font-weight: 600; margin: 20px 0 6px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.5px; }
    p { margin-bottom: 12px; color: #374151; }
    strong { font-weight: 600; color: var(--text); }
    ul, ol { margin: 8px 0 16px 24px; }
    li { margin-bottom: 4px; }
    blockquote { border-left: 3px solid var(--primary); padding: 8px 16px; margin: 16px 0; color: var(--muted); background: var(--accent); border-radius: 0 6px 6px 0; }

    /* Code */
    code { background: #f3f4f6; border-radius: 4px; padding: 2px 6px; font-size: 12px; font-family: 'Menlo', 'Monaco', monospace; color: #c0392b; }
    pre { background: #1e2a1c; color: #a8d5a2; border-radius: 10px; padding: 20px; margin: 16px 0; overflow-x: auto; }
    pre code { background: none; color: inherit; padding: 0; font-size: 13px; }

    /* Tables */
    table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px; }
    th { background: var(--primary); color: white; padding: 10px 14px; text-align: left; font-weight: 600; font-size: 12px; }
    td { padding: 9px 14px; border-bottom: 1px solid var(--border); vertical-align: top; }
    tr:nth-child(even) td { background: #f9fafb; }
    tr:hover td { background: var(--accent); }

    /* Mermaid */
    .mermaid {
      background: #f9fafb;
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 24px;
      margin: 24px 0;
      text-align: center;
      overflow-x: auto;
    }

    /* Print toolbar */
    .print-toolbar {
      position: fixed;
      top: 20px;
      right: 20px;
      display: flex;
      gap: 8px;
      z-index: 100;
    }
    .btn {
      background: var(--primary);
      color: white;
      border: none;
      border-radius: 8px;
      padding: 10px 18px;
      font-size: 13px;
      font-weight: 600;
      cursor: pointer;
      display: flex;
      align-items: center;
      gap: 6px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.15);
    }
    .btn:hover { background: var(--primary-light); }
    .btn-outline { background: white; color: var(--primary); border: 2px solid var(--primary); }
    .btn-outline:hover { background: var(--accent); }

    /* Checklist */
    input[type=checkbox] { width: 14px; height: 14px; margin-right: 6px; accent-color: var(--primary); }
  </style>
</head>
<body>

  <!-- Print toolbar -->
  <div class="print-toolbar no-print">
    <button class="btn btn-outline" onclick="window.history.back()">← Back</button>
    <button class="btn" onclick="window.print()">🖨 Print / Save PDF</button>
  </div>

  <!-- Cover page -->
  <div class="cover">
    <div class="cover-brand">SkolaTech PRD Studio</div>
    <h1>${escapeHtml(appName)}</h1>
    <div class="cover-sub">Complete Build-Ready Blueprint · Generated ${date}</div>
    <div class="cover-meta">
      <div class="cover-stat">
        <div class="cover-stat-label">Blueprint Readiness</div>
        <div class="cover-stat-value ${meta.readinessScore >= 80 ? "ok" : "warn"}">${meta.readinessScore}%</div>
      </div>
      <div class="cover-stat">
        <div class="cover-stat-label">Security Score</div>
        <div class="cover-stat-value ${meta.securityScore >= 70 ? "ok" : "warn"}">${meta.securityScore}/100</div>
      </div>
      <div class="cover-stat">
        <div class="cover-stat-label">Security Level</div>
        <div class="cover-stat-value neutral">${meta.securityLevel.charAt(0).toUpperCase() + meta.securityLevel.slice(1)}</div>
      </div>
      <div class="cover-stat">
        <div class="cover-stat-label">Documents</div>
        <div class="cover-stat-value ok">7</div>
      </div>
    </div>
  </div>

  <!-- Stack -->
  ${meta.stack.length > 0 ? `
  <div class="toc">
    <h2>Technology Stack</h2>
    <table>
      <thead><tr><th>Layer</th><th>Technology</th></tr></thead>
      <tbody>${meta.stack.map(([k, v]) => `<tr><td><strong>${k.charAt(0).toUpperCase() + k.slice(1)}</strong></td><td>${escapeHtml(v)}</td></tr>`).join("")}</tbody>
    </table>
  </div>
  ` : ""}

  <!-- Main content -->
  ${html}

  <script>
    mermaid.initialize({
      startOnLoad: true,
      theme: 'default',
      themeVariables: {
        primaryColor: '#2d5a27',
        primaryTextColor: '#ffffff',
        primaryBorderColor: '#4a7c42',
        lineColor: '#6b7280',
        secondaryColor: '#e8f5e3',
        tertiaryColor: '#f9fafb',
      },
      flowchart: { useMaxWidth: true, htmlLabels: true },
      er: { useMaxWidth: true },
      gantt: { useMaxWidth: true },
    });
  </script>
</body>
</html>`;
}

function escapeHtml(str: string) {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function markdownToHtml(md: string): string {
  const lines = md.split("\n");
  const out: string[] = [];
  let i = 0;
  let inTable = false;
  let tableRows: string[][] = [];

  function flushTable() {
    if (!tableRows.length) return;
    const header = tableRows[0];
    const body = tableRows.slice(2);
    out.push("<table>");
    out.push("<thead><tr>" + header.map((h) => `<th>${processInline(h)}</th>`).join("") + "</tr></thead>");
    out.push("<tbody>");
    body.forEach((row) => {
      out.push("<tr>" + row.map((c) => `<td>${processInline(c)}</td>`).join("") + "</tr>");
    });
    out.push("</tbody></table>");
    tableRows = [];
    inTable = false;
  }

  while (i < lines.length) {
    const line = lines[i];

    // Mermaid code block — keep as-is for Mermaid.js
    if (line.startsWith("```mermaid")) {
      if (inTable) flushTable();
      const mermaidLines: string[] = [];
      i++;
      while (i < lines.length && !lines[i].startsWith("```")) {
        mermaidLines.push(lines[i]);
        i++;
      }
      out.push(`<div class="mermaid">${mermaidLines.join("\n")}</div>`);
      i++;
      continue;
    }

    // Other code blocks
    if (line.startsWith("```")) {
      if (inTable) flushTable();
      const codeLines: string[] = [];
      i++;
      while (i < lines.length && !lines[i].startsWith("```")) {
        codeLines.push(escapeHtml(lines[i]));
        i++;
      }
      out.push(`<pre><code>${codeLines.join("\n")}</code></pre>`);
      i++;
      continue;
    }

    // Table
    if (line.startsWith("|")) {
      inTable = true;
      const cells = line.split("|").filter((_, idx, arr) => idx > 0 && idx < arr.length - 1).map((c) => c.trim());
      tableRows.push(cells);
      i++;
      continue;
    }

    if (inTable && !line.startsWith("|")) flushTable();

    // HR
    if (/^---+$/.test(line.trim())) {
      out.push('<hr class="doc-divider">');
      i++;
      continue;
    }

    // Headings — H1 gets special doc-header treatment
    if (line.startsWith("# ")) {
      const text = line.slice(2);
      const id = text.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      // First H1 is the doc title — wrap in doc-header
      out.push(`<div class="doc-section"><div class="doc-header"><h1 id="${id}">${processInline(text)}</h1></div>`);
      // Find the closing HR and wrap all content
      i++;
      continue;
    }
    if (line.startsWith("## ")) {
      const text = line.slice(3);
      const id = text.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      out.push(`<h2 id="${id}">${processInline(text)}</h2>`);
      i++;
      continue;
    }
    if (line.startsWith("### ")) {
      out.push(`<h3>${processInline(line.slice(4))}</h3>`);
      i++;
      continue;
    }
    if (line.startsWith("#### ")) {
      out.push(`<h4>${processInline(line.slice(5))}</h4>`);
      i++;
      continue;
    }

    // Blockquote
    if (line.startsWith("> ")) {
      out.push(`<blockquote>${processInline(line.slice(2))}</blockquote>`);
      i++;
      continue;
    }

    // Unordered list
    if (/^[-*] /.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^[-*] /.test(lines[i])) {
        items.push(`<li>${processInline(lines[i].replace(/^[-*] /, ""))}</li>`);
        i++;
      }
      out.push("<ul>" + items.join("") + "</ul>");
      continue;
    }

    // Ordered list
    if (/^\d+\. /.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^\d+\. /.test(lines[i])) {
        items.push(`<li>${processInline(lines[i].replace(/^\d+\. /, ""))}</li>`);
        i++;
      }
      out.push("<ol>" + items.join("") + "</ol>");
      continue;
    }

    // Checkbox
    if (/^- \[[ x]\]/.test(line)) {
      const checked = line.includes("[x]");
      const text = line.replace(/^- \[[ x]\] /, "");
      out.push(`<p><label><input type="checkbox" ${checked ? "checked" : ""}> ${processInline(text)}</label></p>`);
      i++;
      continue;
    }

    // Empty line
    if (line.trim() === "") {
      out.push("");
      i++;
      continue;
    }

    // Paragraph
    out.push(`<p>${processInline(line)}</p>`);
    i++;
  }

  if (inTable) flushTable();
  return out.join("\n");
}

function processInline(text: string): string {
  return text
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    .replace(/☐/g, "☐")
    .replace(/☑/g, "☑");
}
